name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js # <<<< THIS IS CRITICAL
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or '20.x' or '22' or '22.x'

      - name: Install Dependencies and Build # This step will now use Node.js v20
        run: npm ci && npm run build
        working-directory: ./task-tracker

      - name: Deploy to Firebase Hosting # This step should also use Node.js v20 from the environment
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKTRACKER4ALL }}
          channelId: live
          projectId: tasktracker4all
