name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main # Or your primary deployment branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js # It's good practice to specify Node version
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or '20', or another LTS version you prefer

      - name: Install Dependencies and Build
        run: npm ci && npm run build
        working-directory: ./task-tracker # <--- THIS IS THE KEY CHANGE

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKTRACKER4ALL }} # Make sure this secret is correctly set in your GitHub repo settings
          channelId: live # Deploys to your live channel
          projectId: tasktracker4all
          # The deploy action will use your firebase.json to determine the public directory